[build]
  publish = "."

# XML files should be served as XML
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"

# IMPORTANT: Don't redirect XML files to HTML
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = [], Country = [], Role = []}

# Explicitly don't redirect sitemap.xml
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = false

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = false

[functions]
  directory = "netlify/functions"